dataAnalysis:dataAnalysis.o
	clang -lm -o dataAnalysis dataAnalysis.o

dataAnalysis.o: dataAnalysis.c dataAnalysisUnited.h stringFunctionsExtended.h floatStack.h frequencyStack.h dataAnalysis.h savingLoadingFunctions.h
	clang -c dataAnalysis.c